version: "3.9"

services:
    backend:
        build:
            context: ./BACKEND/
        command: python manage.py runserver 0.0.0.0:3000
        volumes:
            - ./BACKEND:/app
        ports:
            - "3000:3000"

    frontend:
        build:
            context: ./FRONTEND/
        command: npm start
        depends_on:
            - backend
        volumes:
            - ./FRONTEND:/usr/src/app
            - /usr/src/app/node_modules/
        ports:
            - "8000:8000"
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:3000/
            - PORT=8000
